### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Smitty1298** [Yardanico/pippy#2]
Hey! I'm really interested in pippy however I am having trouble getting it to run. I keep getting this error in the cmd 
Traceback (most recent call last):
  File "console_calc.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

https://i.imgur.com/zMWdAw9.png

**Comment by Yardanico** [comment]
@Smitty1298 you should install requests via pip

**Comment by Smitty1298** [comment]
Thank you so much!
